### ISSUE TITLE
New google API for ChromeCast devices support

### ISSUE THREAD

**Issue by dav-m85** [vincentbernat/dashkiosk#36]
Google published in May a [full fledged API for interacting with ChromeCasts devices](http://googledevelopers.blogspot.ca/2015/05/announcing-new-google-cast-apis.html).

It is a bit sorry that dashkiosk does not support ChromeCasts by default, on the legitimate assumption that nodecastor may be unable to communicate with them after an API update by Google. I understand this was obviously the case before May with the "hack" providen by nodecastor, but now with the official API things may have changed, right ?

Am I totally mistaken here ? If not, well is support for the official API planned for dashkiosk ?

**Comment by vincentbernat** [comment]
Dashkiosk supports Chromecasts by default, but the support is optional and should be enabled through a simple configuration option. You can rely on it as long as you understand that it can break unexpectedly. Google didn't make an incompatible change since nodecastor exists. So, it is relatively safe. There are still other risks with the Chromecasts (notably the fact that the way we use it is unusual and may trigger bugs that are not triggered by regular applications).

Didn't know there was a new API. After a quick look, this is still a proprietary API available only on Android and iOS. No way to use that from Node. Moreover, the API is about remote display. It enables someone to get an OpenGL surface and to draw to it. I suppose that behind the scene, this surface is encoded and sent as a video stream.

So, no, this API doesn't help. Google only releases API for the browser/Android/iOS. nodecastor is a hack to bring an API for Node.

**Comment by dav-m85** [comment]
Thanks for the quick answer :)

I should have provided a better link in the first place, my apologizes: https://github.com/googlecast/CastHelloText-chrome and more specifically https://github.com/googlecast/CastHelloText-chrome/blob/master/chromehellotext.html#L63, just not sure if it allows to actually discover ChromeCasts on the network.

**Comment by vincentbernat** [comment]
This example uses the browser API which is a thin layer on top of the Cast API included in Chrome/Chromium. It cannot be used from Node as it relies on a component in Chromium (this is how nodecastor was written: by looking at this component in Chromium source code).

**Comment by dav-m85** [comment]
The dependency to Chrome was not clear to me (well the naming "Chrome API" should have made me tickle). Thanks for explaining it to me. By the way great work on dashkiosk, I'll have a try installing it tomorrow at work to manage our 6 chromecasts screens.

**Comment by vincentbernat** [comment]
Keep me posted on any problem.
