### ISSUE TITLE
Chromecast very slow page load

### ISSUE THREAD

**Issue by eirik-bakke** [vincentbernat/dashkiosk#41]
Hi there,

I'm using dashkiosk to transmit performance data to TV screens throughout our office. All screens are connected via Chromecast, and are piping team-specific web-dashboards (geckoboard), to the different devices.
The setup looks great, and connections are fairly stable. The server running dashkiosk is hardly breaking a sweat.

If I serve a single page to each screen, everything works great. But ideally I would like to cycle between different pages for each device, but that causes significant delays with the chromecasts.

There's about a 30 second load-time for a chromecast to load another webpage, which seems a bit excessive. A receiver from a browser window loads the same content in under 2 seconds, allowing for smooth and dynamic transitions with frequent updates. But with our chromecast implementation we're either forced to serve static content, or cycle pages very infrequently/slowly.

Any idea why the chromecasts take so long to load content, and is there anything that can be done to improve on this?

Thanks for a fantastic piece of software otherwise. :)

**Comment by vincentbernat** [comment]
The Chromecast is not a very fast. I remember that Geckoboard is a bit heavy for the Chromecast. There is little to do about that. You can try with https://boombatower.github.io/chromecast-dashboard/sender/ to check how much performance you can get from the Chromecast alone. Dashkiosk adds a little overhead because during a transition, the Chromecast should be able to load the new dashboard while the old one is still displayed. You can check if it is related to your issue by adding a blank page between each dashboard. Not really a workaround, but that's to pinpoint if the problem comes from here.

Note however, there is some known issues with the Chromecast that can crash after some time. I don't know if it has been resolved but the issue seems to come from the usage of the iframes. Again, not much to do as the iframe is why Dashkiosk is able to do the work.

If you don't already bought a load of Chromecast devices and are not using them for anything else than Dashkiosk, I find Android devices far more reliable and powerful (note that the wifi may be more problematic with them). If the Chromecast solution is too much trouble, you could try a 50$ android TV stick instead.

**Comment by plitewaikato** [comment]
I worked around the Chromecast crashes by remotely rebooting them on an
hourly schedule.  They're spotted by Dashkiosk immediately upon reboot and
the outage is only about thirty seconds.

**Comment by vincentbernat** [comment]
I don't think there is much to do here. The screencasting feature is quite different since the Chromecast is playing a video stream, while Dashkiosk is asking the Chromecast to evaluate and render HTML/CSS/JS, hence the suggestion to also try with boombatower's sender which is similar.

I'll close the bug unless there is some evidence that everything works fine with boombatower's sender but not Dashkiosk.
