### ISSUE TITLE
JIRA burndown chart bails out when viewed through Dashkiosk

### ISSUE THREAD

**Issue by magjac** [vincentbernat/dashkiosk#42]
Apparently JIRA cannot run within an iFrame, see https://jira.atlassian.com/browse/JRA-20988

They suggest we contact you to hear if you have any experience in or a workaround for this.

We're running Dashkiosk v2.2.4 and haven't yet been able to install the latest version. Any ideas if it might work with the latest version?

**Comment by vincentbernat** [comment]
It won't work either with a more recent version. Jira should not expect to be the top window and due to cross-origin checks, it should not expect to be able to access properties of top window either.

**Comment by magjac** [comment]
OK, thanks. That's what I expected.

**Comment by vincentbernat** [comment]
If you are on Android, very old versions of Dashkiosk didn't have this problem because iframes were not used. See commit 02dac57e971ab64f0f5e9d1e65e654038502f247. However, this is quite different of the actual Dashkiosk. Notably, no admin panel. A browser with automatic tab rotation may be a better fit.

**Comment by magjac** [comment]
Thanks. We're on Ubuntu. We'll find another solution. JIRA hardly fixes anything.
