### ISSUE TITLE
Feature request: Disable animations entirely

### ISSUE THREAD

**Issue by rjgscotland** [vincentbernat/dashkiosk#47]
The slow browser detection doesn't seem to work well and on the Raspberry Pi (even 3) it's very slow to render the transition animation (using Chromium). Could there be an option to just never animate?

**Comment by vincentbernat** [comment]
The threshold is 5 fps. Do you find the animation used is smooth in your case?

Some solutions:
 - in `app/scripts/receiver.js`, remove `benchmark.done(function() {` (as well as the matching `});` a few lines below
 - make it a global runtime option
 - increase the threshold (being able to animate a few particles is easier than do a smooth transition of an heavy-loaded page)
 - add a user-agent blacklist (Raspberry Pi won't perform well because of the absence of hardware acceleration)
 - have a per-receiver checkbox to disable animations

I can easily increase the threshold to 25 fps if you can confirm that this excludes correctly your RPi 3. I can also easily add a blacklist for non-Android ARM user agents. Other possibilities would take more time (and I don't currently have much).

**Comment by rjgscotland** [comment]
Thanks for the response. From using the browser console, it's reporting 7fps, which is just above the threshold. I'll have a play around and see if I can prevent it from animating from your suggestions. A checkbox would be nice though but the blacklist would work too. In any case for my use of cycling through multiple grafana pages I find it distracting having the entire screen slide up and down rather than just a hard cut between the pages even on fast hardware. Another issue that seems to be specific to chromium is that sometimes it will display completely white between pages - this is especially annoying when displaying dark grafana pages. I'm not sure if it's in the scope of dashkiosk to work around this.

**Comment by vincentbernat** [comment]
For the white page, this is a limitation of how Dashkiosk works. Dashboards are embedded into an iframe. While it is possible to know when an iframe is loaded, it's not possible to know how much they are really loaded. JS-enabled pages can therefore declare they are ready while they still have a lot of JS to execute to get an actual page. For each of those pages, you can add a small delay to fix that.

**Comment by rjgscotland** [comment]
Delay didn't help, however, changing background-color to black instead of white in /app/styles/receiver/iframe.less did! :)

**Comment by vincentbernat** [comment]
But this means that you have a page that doesn't load. For example, a page that sets `X-Frame-Options`.

**Comment by rjgscotland** [comment]
I think it's just grafana is really heavyweight for Pi to load in time? Either that or they declare the background styling too late. It's a quick flash of white rather than it sticking on that for a while, so setting iframe to black seems a good enough work-around for my situation.

**Comment by vincentbernat** [comment]
Maybe the JS is waiting for visibility. Having the iframe hidden delays the execution of the JS. Not much can be done with that, I think.

**Comment by vincentbernat** [comment]
You can now use `/receiver-slow` instead of just `/receiver`. This disables any animation. This should solves your initial request. For the further problems, if there is still something to do in Dashkiosk, please open a new issue.
